### ISSUE TITLE
use newer better Chacha20 crate

### ISSUE THREAD

**Issue by david415** [applied-mixnetworks/rust-sphinxcrypto#12]
https://peterreid.github.io/chacha/chacha/index.html
https://github.com/DaGenix/rust-crypto/issues/156

**Comment by burdges** [comment]
There are nice chacha and poly1305 implementations in https://github.com/cesarb/chacha20-poly1305-aead too but currently it does not expose them https://github.com/cesarb/chacha20-poly1305-aead/issues/4  I'll look at these three a bit more closely eventually.

**Comment by david415** [comment]
done.
